name: Bug Bounty Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  bug_bounty:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'  # Use Go 1.21 to ensure compatibility

    - name: Verify Go Version
      run: go version

    - name: Install Subfinder
      run: |
        go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        sudo mv ~/go/bin/subfinder /usr/local/bin/

    - name: Install Amass
      run: |
        go install github.com/OWASP/Amass/v3/...@latest
        sudo mv ~/go/bin/amass /usr/local/bin/

    - name: Install HTTPX
      run: |
        go install github.com/projectdiscovery/httpx/cmd/httpx@latest
        sudo mv ~/go/bin/httpx /usr/local/bin/

    - name: Install Anew
      run: |
        go install github.com/tomnomnom/anew@latest
        sudo mv ~/go/bin/anew /usr/local/bin/

    - name: Run Subfinder
      run: |
        subfinder -d example.com -o subfinder_results.txt

    - name: Run Amass
      run: |
        amass enum -d example.com -o amass_results.txt

    - name: Run HTTPX
      run: |
        cat subfinder_results.txt | httpx -silent -o httpx_results.txt

    - name: Merge Results with Anew
      run: |
        cat subfinder_results.txt amass_results.txt httpx_results.txt | anew final_results.txt

    - name: Commit and Push Results
      run: |
        git config --local user.email "jareddarkweb@gmail.com"
        git config --local user.name "jareddarkweb"
        git add final_results.txt
        git commit -m "Update results"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


