name: Bug Bounty Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  bug_bounty:
    runs-on: ubuntu-latest
    timeout-minutes: 700  # Set a custom timeout for the job

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'  # Use Go 1.21 to ensure compatibility

    - name: Verify Go Version
      run: go version

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Cache Go build
      uses: actions/cache@v3
      with:
        path: ~/go/bin
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build-

    - name: Install Subfinder
      run: |
        echo "Installing Subfinder"
        go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        sudo mv ~/go/bin/subfinder /usr/local/bin/
      timeout-minutes: 10  # Set a timeout for this step

    - name: Install Amass
      run: |
        echo "Installing Amass"
        go install github.com/owasp-amass/amass/v3/...@latest
        sudo mv ~/go/bin/amass /usr/local/bin/
      timeout-minutes: 10  # Set a timeout for this step

    - name: Install HTTPX
      run: |
        echo "Installing HTTPX"
        go install github.com/projectdiscovery/httpx/cmd/httpx@latest
        sudo mv ~/go/bin/httpx /usr/local/bin/
      timeout-minutes: 10  # Set a timeout for this step

    - name: Install Anew
      run: |
        echo "Installing Anew"
        go install github.com/tomnomnom/anew@latest
        sudo mv ~/go/bin/anew /usr/local/bin/
      timeout-minutes: 5  # Set a timeout for this step

    - name: Run Subfinder
      run: |
        echo "Running Subfinder"
        subfinder -d yahoo.com -o subfinder_results.txt
      timeout-minutes: 30  # Set a timeout for this step

    - name: Run Amass
      run: |
        echo "Running Amass"
        amass enum -d yahoo.com -o amass_results.txt
      timeout-minutes: 120  # Increase the timeout for this step to 2 hours

    - name: Run HTTPX
      run: |
        echo "Running HTTPX"
        cat subfinder_results.txt | httpx -silent -o httpx_results.txt
      timeout-minutes: 15  # Set a timeout for this step

    - name: Merge Results with Anew
      run: |
        echo "Merging Results with Anew"
        cat subfinder_results.txt amass_results.txt httpx_results.txt | anew final_results.txt
      timeout-minutes: 5  # Set a timeout for this step

    - name: Commit and Push Results
      run: |
        echo "Committing and Pushing Results"
        git config --local user.email "jareddarkweb@gmail.com"
        git config --local user.name "jareddarkweb"
        git add final_results.txt
        git commit -m "Update results"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      timeout-minutes: 10  # Set a timeout for this step


