name: Bug Bounty Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  bug_bounty:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Install Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y curl unzip
        # Install Subfinder
        GO111MODULE=on go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        sudo mv ~/go/bin/subfinder /usr/local/bin/subfinder
        # Install Amass
        GO111MODULE=on go install -v github.com/OWASP/Amass/v3/...@master
        sudo mv ~/go/bin/amass /usr/local/bin/amass
        # Install HTTPX
        GO111MODULE=on go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
        sudo mv ~/go/bin/httpx /usr/local/bin/httpx
        # Install Anew
        GO111MODULE=on go install -v github.com/tomnomnom/anew@latest
        sudo mv ~/go/bin/anew /usr/local/bin/anew

    - name: Verify Installation
      run: |
        subfinder -version
        amass -version
        httpx -version
        anew -version

    - name: Run Subfinder
      run: |
        subfinder -d example.com -o subfinder_results.txt

    - name: Run Amass
      run: |
        amass enum -d example.com -o amass_results.txt

    - name: Run HTTPX
      run: |
        cat subfinder_results.txt | httpx -silent -o httpx_results.txt

    - name: Merge Results with Anew
      run: |
        cat subfinder_results.txt amass_results.txt httpx_results.txt | anew final_results.txt

    - name: Commit and Push Results
      run: |
        git config --local user.email "jareddarkweb@gmail.com"
        git config --local user.name "jareddarkweb"
        git add final_results.txt
        git commit -m "Update results"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



